/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package program2;

import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author jorge
 */
public class Program2GUI extends javax.swing.JFrame {

    /**
     * Creates new form Program2GUI
     */
    public Program2GUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        prompt = new javax.swing.JLabel();
        theInput = new javax.swing.JTextField();
        encodedMess = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lowercase = new javax.swing.JButton();
        asIs = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        freqTabl = new javax.swing.JLabel();
        binTabl = new javax.swing.JLabel();
        out = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        prompt.setText("Enter text to Huffman Tree");

        theInput.setText("Enter text...");

        encodedMess.setText("");

        lowercase.setText("Lowercase");
        lowercase.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                lowercaseInputMethodTextChanged(evt);
            }
        });
        lowercase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lowercaseActionPerformed(evt);
            }
        });

        asIs.setText("As is");
        asIs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                asIsActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel2.setText("Frequency Table");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel5.setText("Binary Table");

        freqTabl.setDisplayedMnemonic(' ');
        freqTabl.setText("jLabel6");

        binTabl.setText("jLabel6");

        out.setText("See output.txt for output - the program requires exit to run again.");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(out)
                    .addComponent(jLabel4)
                    .addComponent(prompt)
                    .addComponent(encodedMess)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(lowercase)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(asIs))
                        .addComponent(theInput, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 347, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel2)
                                .addComponent(freqTabl))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(binTabl)
                                .addComponent(jLabel5)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(prompt)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(theInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lowercase)
                    .addComponent(asIs))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(encodedMess)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(freqTabl)
                    .addComponent(binTabl))
                .addGap(66, 66, 66)
                .addComponent(out)
                .addContainerGap(66, Short.MAX_VALUE))
        );

        encodedMess.setVisible(false);
        freqTabl.setVisible(false);
        binTabl.setVisible(false);
        out.setVisible(false);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void asIsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_asIsActionPerformed
        String leInput = theInput.getText();
        if (leInput.contains(".")) {
            Program2.getString(true, false, leInput);
        } else {
            Program2.getString(false, false, leInput);
        }
        try {
            update();
        } catch (IOException ex) {
            Logger.getLogger(Program2GUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_asIsActionPerformed

    private void lowercaseInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_lowercaseInputMethodTextChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_lowercaseInputMethodTextChanged

    private void lowercaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lowercaseActionPerformed
        String leInput = theInput.getText();
        if (leInput.contains(".")) {
            Program2.getString(true, true, leInput);
        } else {
            Program2.getString(false, true, leInput);
        }
        try {
            update();
        } catch (IOException ex) {
            Logger.getLogger(Program2GUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_lowercaseActionPerformed

    private void update() throws IOException {
        Program2.main(null);
        freqTabl.setText(Program2.freqMapStr);
        binTabl.setText(Program2.binMapStr);
        freqTabl.setVisible(true);
        binTabl.setVisible(true);
        encodedMess.setText("Encoded Message: " + Program2.encode());
        encodedMess.setVisible(true);
        out.setVisible(true);
        pack();
        
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Program2GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Program2GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Program2GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Program2GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Program2GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton asIs;
    private javax.swing.JLabel binTabl;
    private javax.swing.JLabel encodedMess;
    private javax.swing.JLabel freqTabl;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton lowercase;
    private javax.swing.JLabel out;
    private javax.swing.JLabel prompt;
    private javax.swing.JTextField theInput;
    // End of variables declaration//GEN-END:variables
}
